export type UseCaseStatus = "active" | "scheduled" | "building";

export interface UseCase {
  id: string;
  title: string;
  category: string;
  description: string;
  howItWorks: string[];
  outcome: string;
  status: UseCaseStatus;
  schedule?: string;
  privacyNote?: string;
  livePreview?: {
    label: string;
    value: string;
  }[];
  icon: string;
  tags: string[];
}

export const USE_CASES: UseCase[] = [
  {
    id: "morning-briefing",
    title: "Morning Briefing",
    category: "Executive Intelligence",
    description: "A personalized daily brief delivered in two parts: calendar+email at 6:25 AM and AI news at 6:35 AM via Telegram.",
    howItWorks: [
      "Fetches today's calendar via Microsoft Graph API",
      "Pulls top unread emails, cross-references with meetings",
      "Searches the web for AI news from the past 24 hours",
      "Formats and delivers calendar+email briefing at 6:25 AM",
      "Formats and delivers AI news briefing at 6:35 AM",
    ],
    outcome: "Zero manual research before the first meeting. Walk in prepared.",
    status: "active",
    schedule: "Daily at 6:25 AM and 6:35 AM PT",
    privacyNote: "Meeting titles and email senders anonymized in demo",
    livePreview: [
      { label: "Calendar run", value: "6:25 AM daily" },
      { label: "AI news run", value: "6:35 AM daily" },
      { label: "Last delivered", value: "Today" },
    ],
    icon: "☀️",
    tags: ["Calendar", "Email", "AI News", "Telegram"],
  },
  {
    id: "email-triage",
    title: "Email Triage",
    category: "Executive Intelligence",
    description: "Every evening, surfaces emails from the past 48 hours that likely need a reply — filtered by sender, urgency signals, and action language.",
    howItWorks: [
      "Fetches recent emails via Microsoft Graph API",
      "Filters out automated notifications, calendar invites, ServiceNow alerts",
      "Scores remaining emails by: sender seniority, action language, thread activity",
      "Delivers a clean 'Needs Your Reply' list to Telegram at 5:30 PM",
    ],
    outcome: "No important email goes unanswered. Inbox zero mindset without the work.",
    status: "active",
    schedule: "Weekdays at 5:30 PM PT",
    privacyNote: "Sender names anonymized in demo",
    livePreview: [
      { label: "Next run", value: "5:30 PM daily" },
      { label: "Window", value: "Last 48 hours" },
      { label: "Avg flagged", value: "3–6 emails" },
    ],
    icon: "📬",
    tags: ["Email", "Microsoft Graph", "Telegram"],
  },
  {
    id: "gmail-school-notifications",
    title: "School Notification Triage",
    category: "Family Ops",
    description: "A read-only Gmail scan for school-related messages in Brett's personal account, separating true action items from newsletters and FYI noise.",
    howItWorks: [
      "Uses Google OAuth with gmail.readonly scope only",
      "Searches recent personal Gmail messages for school, district, teacher, attendance, permission, and deadline signals",
      "Scores messages by action terms, sender patterns, unread status, and low-priority newsletter signals",
      "Saves a local markdown brief and sends a concise Telegram summary only when something needs attention",
    ],
    outcome: "Important school messages surface without manually digging through the personal inbox.",
    status: "scheduled",
    schedule: "Weekdays at 7:00 AM and 3:00 PM PT after Gmail consent is completed",
    privacyNote: "Read-only Gmail access; Telegram summary excludes full email bodies",
    livePreview: [
      { label: "Access", value: "gmail.readonly" },
      { label: "Status", value: "OAuth pending" },
      { label: "Output", value: "Need-read + skim list" },
    ],
    icon: "🏫",
    tags: ["Gmail", "Family", "School", "Telegram", "Read-only"],
  },
  {
    id: "linkedin-machine",
    title: "LinkedIn Post Machine",
    category: "Thought Leadership",
    description: "Every Friday, drafts two instructional LinkedIn posts based on the week's activity — sourced from email, Teams channels, and 1:1 chats.",
    howItWorks: [
      "Scans email for project milestones, wins, and notable outcomes",
      "Reads Teams channels: AI Use Cases, TritonAI Internal, AI Admin Workgroup",
      "Checks 1:1 chats with direct reports and key stakeholders",
      "Drafts two posts: one use case walkthrough, one outcome/numbers post",
      "Delivers to Telegram for review — reply 'post 1' or 'tweak 1: [notes]'",
    ],
    outcome: "Consistent LinkedIn presence without the time investment. Instructional posts that build credibility.",
    status: "active",
    schedule: "Fridays at 5:00 PM PT",
    livePreview: [
      { label: "Next draft", value: "Friday 5 PM" },
      { label: "Sources", value: "Email · Teams" },
      { label: "Format", value: "Use Case + Numbers" },
    ],
    icon: "✍️",
    tags: ["LinkedIn", "Teams", "Email", "Content"],
  },
  {
    id: "tritongpt-intel",
    title: "TritonAI Intel Brief",
    category: "Competitive Intelligence",
    description: "Every Sunday morning, a strategic brief on what peer universities and competitors are doing in AI — so the TritonAI team stays ahead.",
    howItWorks: [
      "Searches the web for institutional AI deployments at peer universities",
      "Monitors AI vendor and platform news targeting higher education",
      "Tracks governance, policy, and compliance developments",
      "Flags early signals relevant to TritonAI roadmap",
      "Delivered to Telegram every Sunday at 8:00 AM",
    ],
    outcome: "Walk into every meeting and conference knowing the competitive landscape cold.",
    status: "active",
    schedule: "Sundays at 8:00 AM PT",
    livePreview: [
      { label: "Next run", value: "Sunday 8 AM" },
      { label: "Coverage", value: "UC + R1 peers" },
      { label: "Sections", value: "4 categories" },
    ],
    icon: "🔭",
    tags: ["Higher Ed", "TritonAI", "Competitive Intel", "Strategy"],
  },
  {
    id: "opportunity-scan",
    title: "Daily Opportunity Scan",
    category: "Executive Intelligence",
    description: "Every morning at 7:00 AM, cross-references the knowledge graph and UCSD data sources to surface process gaps, software needs, vendor decisions, and partnership opportunities — with numbered actions you can execute by replying.",
    howItWorks: [
      "Loads Brett's knowledge graph (people, projects, relationships)",
      "Loads UCSD data source catalog (available campus systems)",
      "Researches recent higher ed AI use cases and campus technology innovations",
      "Scores ideas against impact, feasibility, Brett relevance, data availability, and competitive urgency",
      "Surfaces the single highest-scoring idea with required data sources and build complexity",
      "Delivers to Telegram — reply with a number to act on the finding",
    ],
    outcome: "Turn passive information overload into a prioritized action list. Surface software ideas and process gaps before they become bigger problems.",
    status: "active",
    schedule: "Daily at 7:00 AM PT",
    livePreview: [
      { label: "Next run", value: "7:00 AM daily" },
      { label: "Latest pick", value: "Workforce onboarding orchestrator" },
      { label: "Signal", value: "ServiceNow + UC Path + Graph" },
    ],
    icon: "🔍",
    tags: ["Knowledge Graph", "UCSD Data", "Research", "Intelligence"],
  },
  {
    id: "evening-reflection",
    title: "Evening Reflection",
    category: "Executive Intelligence",
    description: "A daily end-of-day recap — what worked, what didn't, what needs attention tomorrow. Honest, direct, under 200 words.",
    howItWorks: [
      "Reviews the day's activity and conversation context",
      "Identifies friction points and wins",
      "Cross-references emails needing reply",
      "Surfaces tomorrow's calendar highlights",
      "Delivered to Telegram at 5:30 PM with the email triage",
    ],
    outcome: "End each day with clarity. No loose ends slipping through.",
    status: "active",
    schedule: "Weekdays at 5:30 PM PT",
    livePreview: [
      { label: "Next run", value: "5:30 PM daily" },
      { label: "Includes", value: "Wins · Gaps · Next day" },
    ],
    icon: "🪞",
    tags: ["Reflection", "Productivity", "Telegram"],
  },
  {
    id: "teams-integration",
    title: "Teams & Exchange Integration",
    category: "Data Sources",
    description: "Full read access to Microsoft 365 — 39 Teams, all channels, 1:1 chats, email, and calendar — feeding context into every automation.",
    howItWorks: [
      "OAuth device flow authentication via Microsoft tenant",
      "Delegated permissions: Mail.Read, Calendars.Read, Chat.Read, ChannelMessage.Read.All",
      "Token auto-refreshed hourly to maintain access",
      "Feeds data to: Morning Briefing, Email Triage, LinkedIn Machine, Evening Reflection",
    ],
    outcome: "All automations have live institutional context. No copy-pasting. No context switching.",
    status: "active",
    livePreview: [
      { label: "Teams", value: "39 workspaces" },
      { label: "Chats", value: "1:1s + group threads" },
      { label: "Token refresh", value: "Every hour" },
    ],
    icon: "🔗",
    tags: ["Microsoft 365", "Teams", "Exchange", "OAuth"],
  },
  {
    id: "local-llm",
    title: "Local LLM (Gemma 4 27B)",
    category: "Infrastructure",
    description: "A locally-hosted large language model running on the Mac mini via Ollama — for privacy-sensitive tasks that shouldn't leave the building.",
    howItWorks: [
      "Gemma 4 27B running via Ollama on Mac mini",
      "Apple Metal GPU acceleration",
      "Registered as a model provider in OpenClaw",
      "Switch with /model gemma4 — switch back with /model sonnet",
    ],
    outcome: "Sensitive institutional data stays on-prem. Zero API costs for local tasks.",
    status: "active",
    livePreview: [
      { label: "Model", value: "Gemma 4 27B" },
      { label: "Hardware", value: "Apple Silicon" },
      { label: "Alias", value: "/model gemma4" },
    ],
    icon: "🧠",
    tags: ["Local AI", "Ollama", "Privacy", "On-Prem"],
  },
  {
    id: "pre-meeting-brief",
    title: "Pre-Meeting Brief",
    category: "Executive Intelligence",
    description: "15 minutes before each meeting, relevant email context and talking points surface automatically — so every meeting starts informed.",
    howItWorks: [
      "Monitors calendar for upcoming meetings",
      "Searches email and Teams for threads related to the meeting topic or attendees",
      "Generates a 3-bullet context brief",
      "Delivers to Telegram 15 minutes before start time",
    ],
    outcome: "Walk into every meeting knowing the recent context. No last-minute scrambling.",
    status: "building",
    icon: "📋",
    tags: ["Calendar", "Email", "Teams", "Meetings"],
  },
  {
    id: "email-drafts",
    title: "Email Drafts",
    category: "Development",
    description: "A searchable library of AI-assisted email drafts saved from Henry's voice-drafting workflow — each draft includes the original request, generated content, self-critique, and context used.",
    howItWorks: [
      "Henry's Brett-voice drafter skill saves every draft to workspace/docs/",
      "Files follow naming pattern: draft-email-<topic>-YYYY-MM-DD.md",
      "Each draft contains: subject line, body, voice notes, self-critique, and sources",
      "Mission Control scans docs/ for draft-email-* files and displays them",
      "Clicking a draft opens the full markdown in a readable view",
    ],
    outcome: "Never lose a draft. Review, refine, and reuse AI-assisted writing while keeping Brett's voice and institutional context.",
    status: "building",
    livePreview: [
      { label: "Location", value: "workspace/docs/" },
      { label: "Pattern", value: "draft-email-*.md" },
      { label: "Latest", value: "Xavier Llamas (Google)" },
    ],
    icon: "✉️",
    tags: ["Email", "Docs", "Writing", "AI Assistance"],
  },
  {
    id: "mission-control",
    title: "Mission Control",
    category: "Development",
    description: "A personal AI operations center — 9 screens covering agent org chart, Kanban task board, cron calendar, project hub with reverse-prompting, memory browser, docs library, live system graph, TritonAI adoption pulse, and executive decision queue.",
    howItWorks: [
      "Team screen: mission statement, agent org chart, live force-directed system graph (HTML Canvas)",
      "Tasks: Kanban board (Backlog/In Progress/Blocked/Done) + live activity feed, heartbeat-integrated",
      "Calendar: all cron jobs visualized with live status from OpenClaw",
      "Projects: 6 campus initiatives with 'What can we do right now?' reverse-prompting via Claude",
      "Memory: daily journal browser + long-term memory editor reading from workspace files",
      "Docs: searchable markdown library scanning the full workspace directory",
      "Custom tools: TritonAI Adoption Pulse (dept grid) + Executive Decision Queue (pending approvals)",
    ],
    outcome: "A single ops center for Brett — task management, AI activity monitoring, campus initiative tracking, and institutional memory in one Linear-inspired dark dashboard.",
    status: "active",
    livePreview: [
      { label: "Screens", value: "9 total" },
      { label: "Custom tools", value: "2 built" },
      { label: "Stack", value: "Next.js + Vercel" },
    ],
    privacyNote: "Memory and weekly synthesis changes should be reflected here when the curated memory layer changes.",
    icon: "🎛️",
    tags: ["Next.js", "Vercel", "Multi-Agent", "Operations", "Canvas"],
  },
  {
    id: "ai-automation-dashboard",
    title: "AI Automation Stack Dashboard",
    category: "Development",
    description: "A live showcase dashboard built with Next.js and deployed on Vercel — displaying all active automations, data sources, and infrastructure with real-time status pulled from OpenClaw.",
    howItWorks: [
      "Built with Software Blueprint — Next.js App Router, MUI color system, CSS Modules",
      "Live automation status fetched from OpenClaw cron API at page load",
      "Hourly GitHub push from Mac mini keeps Vercel deployment current",
      "Password-protected via NextAuth.js — single owner access",
      "Each card shows last run, next run, and delivery status in real time",
    ],
    outcome: "A single URL to share at conferences and meetings that demonstrates the full AI automation stack in action — no slides needed.",
    status: "active",
    livePreview: [
      { label: "Stack", value: "Next.js + Vercel" },
      { label: "Auth", value: "NextAuth.js" },
      { label: "Updates", value: "Hourly" },
    ],
    icon: "📊",
    tags: ["Next.js", "Vercel", "GitHub", "OpenClaw", "Dashboard"],
  },
  {
    id: "software-blueprint",
    title: "Software Blueprint",
    category: "Development",
    description: "A 6-stage multi-agent development framework that turns a plain-language brief into a deployed app, with explicit model routing for planning, architecture, building, QA, deploy, and docs.",
    howItWorks: [
      "Planning Agent uses Claude Opus as primary reasoner to write PLAN.md and lock storage, API surface, and data decisions",
      "Architect Agent uses Claude Opus to turn PLAN.md into a detailed SPEC.md with design, accessibility, and implementation guidance",
      "Builder Agent uses Codex / GPT-5.4 as primary code generator, with Claude Sonnet fallback and Nemotron for compliance-sensitive builds",
      "QA runs deterministic npm/build checks first, with optional Claude Sonnet error analysis only when failures occur",
      "Deploy uses CLI automation for GitHub and Vercel, with optional Claude Sonnet debugging on deployment failures",
      "Docs uses local Gemma 4 on the Mac mini for boilerplate and Claude Sonnet for final polish",
    ],
    outcome: "Say 'build me X' via Telegram and get a production-grade app with better planning discipline, clearer model roles, and explicit human approvals at plan, spec, and deploy checkpoints.",
    status: "active",
    livePreview: [
      { label: "Stages", value: "6-stage pipeline" },
      { label: "Primary models", value: "Opus + Codex + Gemma 4" },
      { label: "Default stack", value: "Next.js + Vercel" },
    ],
    icon: "🏗️",
    tags: ["Multi-Agent", "Opus", "Codex", "Gemma 4", "Vercel", "Accessibility"],
  },
  {
    id: "briefing-ai-news",
    title: "AI News Brief",
    category: "Executive Intelligence",
    description: "Daily web search for the most relevant AI and higher education technology developments — filtered for what matters to a CTO at a major research university.",
    howItWorks: [
      "Searches the web for AI news from the past 24 hours",
      "Filters for higher education, enterprise AI, and governance topics",
      "Ranks stories by relevance to TritonAI and UC San Diego strategy",
      "Summarizes top 3-5 items in plain language for fast intake",
      "Delivered to Telegram each morning",
    ],
    outcome: "Stay current on AI without spending an hour reading news. Show up to meetings informed.",
    status: "active",
    schedule: "Daily at 6:35 AM PT",
    livePreview: [
      { label: "Coverage", value: "AI + EdTech" },
      { label: "Stories", value: "3-5 per day" },
      { label: "Filter", value: "UC relevance" },
    ],
    icon: "📰",
    tags: ["AI News", "Higher Ed", "Web Search", "Telegram"],
  },
  {
    id: "relationship-health",
    title: "Relationship Health Check",
    category: "Executive Intelligence",
    description: "Weekly scan of email and calendar to surface relationships that are going quiet — vendors, peers, direct reports, and partners who haven't been touched in a while.",
    howItWorks: [
      "Reads email from past 30 days via Microsoft Graph",
      "Cross-references against known stakeholder list",
      "Flags contacts with no interaction in 2+ weeks",
      "Groups by relationship type: direct report, peer, vendor, external",
      "Delivered to Telegram every Friday at 4:00 PM",
    ],
    outcome: "No key relationship goes cold by accident. Stay intentional about who you're investing time with.",
    status: "active",
    schedule: "Fridays at 4:00 PM PT",
    livePreview: [
      { label: "Scope", value: "30-day window" },
      { label: "Threshold", value: "14 days silent" },
      { label: "Categories", value: "4 groups" },
    ],
    icon: "🤝",
    tags: ["Relationships", "Email", "Microsoft Graph", "CRM"],
  },
  {
    id: "student-signals",
    title: "Student Pain Signal Monitor",
    category: "Competitive Intelligence",
    description: "Daily scan of Reddit, campus forums, and social signals to surface technology friction points UC San Diego students are experiencing — a ground-truth feed for IT strategy.",
    howItWorks: [
      "Searches Reddit (r/UCSD, r/college, higher ed forums)",
      "Scans for service complaints, workaround threads, tool requests",
      "Categorizes signals: VPN, Wi-Fi, Canvas, TritonLink, email, printing",
      "Surfaces top 3-5 pain themes with example quotes",
      "Delivered to Telegram daily at 7:30 AM",
    ],
    outcome: "Hear from students before problems escalate to tickets or Reddit mobs. Proactive IT strategy from real signal.",
    status: "active",
    schedule: "Daily at 7:30 AM PT",
    livePreview: [
      { label: "Sources", value: "Reddit + forums" },
      { label: "Categories", value: "6 service areas" },
      { label: "Output", value: "Top pain themes" },
    ],
    icon: "🎓",
    tags: ["Student Experience", "Reddit", "Web Search", "IT Strategy"],
  },
  {
    id: "it-job-monitor",
    title: "IT Leadership Job Monitor",
    category: "Competitive Intelligence",
    description: "Daily scan for executive and director-level IT roles at southern UC campuses — so Brett tracks who's moving, which campuses are hiring, and what skills they're targeting.",
    howItWorks: [
      "Searches UC campus job boards daily at 8:00 AM",
      "Filters for IT leadership roles above $250K compensation",
      "Covers southern campuses: UCLA, UC Irvine, UC Riverside, UC Santa Barbara",
      "Flags new postings and role changes since last run",
      "Delivers Telegram summary with titles, campuses, and links",
    ],
    outcome: "Stay aware of the IT leadership landscape across the UC system. Know who's hiring before it becomes public news.",
    status: "active",
    schedule: "Daily at 8:00 AM PT",
    livePreview: [
      { label: "Campuses", value: "4 southern UC" },
      { label: "Threshold", value: ">$250K roles" },
      { label: "Scope", value: "IT leadership" },
    ],
    icon: "💼",
    tags: ["Higher Ed", "Talent Intel", "UC System", "Job Market"],
  },
  {
    id: "knowledge-graph",
    title: "Knowledge Graph",
    category: "Infrastructure",
    description: "A live graph of people, projects, and organizations in Brett's professional world — rebuilt daily from email, calendar, and documents.",
    howItWorks: [
      "Extracts entities from email, meetings, and documents",
      "Maps relationships: reports-to, works-with, vendor, peer, partner",
      "Rebuilds nightly at 6:20 AM to capture recent additions",
      "Stored as JSON at data/knowledge-graph.json",
      "Powering semantic lookups in Meeting Prep, Opportunity Scan, and Briefings",
    ],
    outcome: "Every automation has instant access to who's who — no repeated context-setting.",
    status: "active",
    schedule: "Daily at 6:20 AM PT",
    livePreview: [
      { label: "Nodes", value: "143 entities" },
      { label: "Edges", value: "163 relationships" },
      { label: "Sources", value: "Email · Calendar · Docs" },
    ],
    icon: "🕸️",
    tags: ["Knowledge Graph", "NLP", "Entity Extraction", "Infrastructure"],
  },
  {
    id: "overnight-code-maintenance",
    title: "Overnight Code Maintenance",
    category: "Development",
    description: "A Tuesday and Friday overnight agent that reviews open tasks, tidies workspace files, checks for dependency updates, and ships small quality improvements without waking anyone up.",
    howItWorks: [
      "Runs at 2:00 AM Tuesday and Friday",
      "Reviews task backlog for quick wins",
      "Checks henry-dashboard and henry-api for code quality issues",
      "Scans workspace for stale or orphaned files",
      "Commits and pushes improvements to GitHub",
    ],
    outcome: "Technical debt shrinks automatically. Come in Monday morning to a slightly cleaner codebase.",
    status: "active",
    schedule: "Tues + Fri at 2:00 AM PT",
    livePreview: [
      { label: "Schedule", value: "Tue + Fri 2 AM" },
      { label: "Focus", value: "Quality + Cleanup" },
      { label: "Output", value: "GitHub commits" },
    ],
    icon: "🌙",
    tags: ["Maintenance", "GitHub", "Code Quality", "Automation"],
  },
  {
    id: "granola-meeting-debrief",
    title: "Granola Meeting Debrief",
    category: "Executive Intelligence",
    description: "Every weekday at 6:15 PM, syncs and summarizes today's meetings from Granola — extracting decisions, action items, and Brett's commitments — then creates backlog tasks for items he owns.",
    howItWorks: [
      "Runs the Granola feeder to sync today's meetings",
      "For each meeting, fetches the full note with transcript from Granola API",
      "Extracts key decisions, action items with owners, and Brett's commitments",
      "Applies context-aware filtering: only creates tasks where Brett is the driver",
      "Posts filtered action items as backlog tasks in Mission Control",
      "Saves a clean debrief markdown file to workspace/docs/",
    ],
    outcome: "Never miss a commitment or decision from meetings. Automatically turns meeting outcomes into tracked action items.",
    status: "active",
    schedule: "Weekdays at 6:15 PM PT",
    livePreview: [
      { label: "Next run", value: "Weekdays 6:15 PM" },
      { label: "Last debrief", value: "Today" },
    ],
    icon: "📋",
    tags: ["Meetings", "Granola", "Action Items", "Telegram"],
  },
  {
    id: "tax-reminder",
    title: "Tax Reminder",
    category: "Personal",
    description: "Every Monday, Wednesday, and Friday at 10:00 AM, reminds Brett to finish his taxes in TurboTax before the April 15 deadline.",
    howItWorks: [
      "Checks if tax deadline has passed",
      "If not past deadline, sends a direct nudge via Telegram",
      "Increases urgency if it's been more than a week since last reminder",
      "Automatically disables after April 15",
    ],
    outcome: "Stay on top of personal tax deadlines without mental overhead.",
    status: "active",
    schedule: "Mon/Wed/Fri at 10:00 AM PT",
    livePreview: [
      { label: "Next run", value: "Next scheduled day" },
      { label: "Deadline", value: "April 15" },
    ],
    icon: "🧾",
    tags: ["Personal", "Taxes", "Reminder"],
  },
  {
    id: "backlog-tasks",
    title: "Backlog Tasks Report",
    category: "Development",
    description: "Twice daily (9:00 AM and 6:00 PM), lists all current backlog tasks from the Mission Control system so Brett can see what needs attention.",
    howItWorks: [
      "Fetches all tasks from the Mission Control API",
      "Filters for tasks with status 'backlog'",
      "Formats them as a numbered list with title, date, category, and priority",
      "Sends the list to Brett via Telegram",
      "If no backlog tasks, sends: '📋 No backlog tasks currently.'",
    ],
    outcome: "Always know what's in your backlog. No forgotten tasks slipping through the cracks.",
    status: "active",
    schedule: "Daily at 9:00 AM and 6:00 PM PT",
    livePreview: [
      { label: "Next run", value: "Next scheduled time" },
      { label: "Backlog count", value: "Check Mission Control" },
    ],
    icon: "📋",
    tags: ["Tasks", "Backlog", "Telegram"],
  },
  {
    id: "stale-briefing-alert",
    title: "Stale Briefing Alert",
    category: "Executive Intelligence",
    description: "Every weekday at 7:30 AM, verifies that today's morning briefings (calendar and AI news) were generated successfully and alerts Brett if any are missing.",
    howItWorks: [
      "Checks for existence of today's calendar briefing markdown file",
      "Checks for existence of today's AI news digest markdown file",
      "Checks for existence of today's opportunity scan markdown file",
      "If any are missing, alerts Brett with: '☕ Morning briefing gap — [missing items]. Likely cause: Graph token expired or cron timed out. Check `openclaw cron list`.'",
      "If all present, replies silently with HEARTBEAT_OK",
    ],
    outcome: "Never miss a briefing due to silent failures. Get alerted immediately when automations don't run.",
    status: "active",
    schedule: "Weekdays at 7:30 AM PT",
    livePreview: [
      { label: "Next run", value: "Weekdays 7:30 AM" },
      { label: "Status", value: "All briefings generated" },
    ],
    icon: "☕",
    tags: ["Monitoring", "Briefings", "Alert"],
  },
  {
    id: "henry-enhancement-sprint",
    title: "Henry Enhancement Sprint",
    category: "Development",
    description: "Every weekday at 6:30 AM, continues the Henry enhancement program by picking one highest-priority not-done enhancement task, implementing a substantial increment, and announcing progress to Brett.",
    howItWorks: [
      "Checks the Henry backlog for enhancement tasks (task-henry-enh-001 through task-henry-enh-005 and follow-ons)",
      "Picks the highest-priority not-done item",
      "Moves it to in-progress if possible",
      "Completes one substantial implementation increment",
      "Updates task notes/status",
      "Announces a concise progress summary to Brett",
    ],
    outcome: "Steady, visible improvements to Mission Control without large time investments.",
    status: "active",
    schedule: "Weekdays at 6:30 AM PT",
    livePreview: [
      { label: "Next run", value: "Weekdays 6:30 AM" },
      { label: "Current focus", value: "task-henry-enh-009 parity sync shipped" },
    ],
    icon: "⚡",
    tags: ["Development", "Mission Control", "Enhancement"],
  },
  {
    id: "openclaw-update-watch",
    title: "OpenClaw Update Watch",
    category: "Infrastructure",
    description: "Every night at 9:15 PM, checks for newer OpenClaw versions, applies updates if available, and summarizes changes for Brett.",
    howItWorks: [
      "Determines the currently installed OpenClaw version",
      "Checks whether a newer OpenClaw version is available",
      "If no update: appends brief no-update note to changelog (if none in past 3 days)",
      "If update available: runs official OpenClaw self-update",
      "Captures old and new versions",
      "Summarizes important changes in plain English",
      "Appends dated entry to OpenClaw changelog",
      "Also appends short note to today's daily memory file",
      "On failure: appends failure note and notifies Brett via Telegram",
    ],
    outcome: "Stay current with OpenClaw improvements without manual version checking.",
    status: "active",
    schedule: "Nightly at 9:15 PM PT",
    livePreview: [
      { label: "Next run", value: "Tonight 9:15 PM" },
      { label: "Current version", value: "2026.4.5" },
    ],
    icon: "🔄",
    tags: ["Updates", "Maintenance", "Version"],
  },
  {
    id: "uncommitted-changes-check",
    title: "Uncommitted Changes Check",
    category: "Development",
    description: "Every Friday at 6:00 PM, scans git repos in the workspace for uncommitted changes, auto-commits and pushes them, then reports what was saved.",
    howItWorks: [
      "Checks these repos for uncommitted changes: workspace, mission-control-app, henry-api, henry-dashboard",
      "For each repo with changes: runs `git status --porcelain`",
      "If any repo has uncommitted changes: auto-commits with message 'chore: auto-save uncommitted work (weekly watchdog)' and pushes",
      "Messages Brett with what was committed: '💾 Weekly save — committed uncommitted changes in [repos]. All pushed.'",
      "If everything is clean: replies HEARTBEAT_OK (no message)",
    ],
    outcome: "Never lose work due to forgotten commits. Weekly auto-save keeps everything backed up.",
    status: "active",
    schedule: "Fridays at 6:00 PM PT",
    livePreview: [
      { label: "Next run", value: "Next Friday 6:00 PM" },
      { label: "Status", value: "All repos clean" },
    ],
    icon: "💾",
    tags: ["Git", "Backup", "Automation"],
  },
  {
    id: "website-ai-digest-sync",
    title: "Website AI Digest Sync",
    category: "Development",
    description: "Daily, refreshes brettcpollak.com's AI Digest page from this week's workspace digest headlines using public-facing framing and pushes the site when content changes.",
    howItWorks: [
      "Keeps https://brettcpollak.com/ai-digest showing the current Monday-anchored week's digests",
      "Ensures website version remains PUBLIC-FACING: removes personal/internal framing",
      "Omits missing digest days rather than inventing content",
      "If no content changes: exits without committing",
      "Uses exact paths: workspace digest source → /Users/brettpollak/.openclaw/workspace/docs",
      "Site repo local clone → /tmp/brettpollak-website",
      "Site repo remote → https://github.com/bpollak/brettpollak-website.git",
      "Steps: clone/pull, run update script, preserve public-safe rendering, check for changes, build and push if changed",
    ],
    outcome: "Brett's personal website stays current with his AI digest content automatically.",
    status: "active",
    schedule: "Daily",
    livePreview: [
      { label: "Next run", value: "Today" },
      { label: "Content status", value: "Check website" },
    ],
    icon: "🌐",
    tags: ["Website", "Content", "Sync"],
  },
  {
    id: "cron-failure-monitor",
    title: "Cron Failure Monitor",
    category: "Infrastructure",
    description: "Every Monday at 8:00 AM, audits cron health: lists jobs with errors, disabled jobs, repeated timeouts, and sends Brett a summary if problems are found.",
    howItWorks: [
      "Run `openclaw cron list --json` and check all jobs",
      "List any jobs with errors or that haven't run successfully in the past 7 days",
      "List any disabled jobs that might have been accidentally turned off",
      "Check for jobs with repeated timeouts (look at recent run history if available)",
      "Send Brett a brief Telegram summary ONLY if there are problems. Format: '🔧 Weekly Cron Audit — [N] issues found:' then bullet each problem with job name and what's wrong.",
      "If everything looks healthy, reply HEARTBEAT_OK (no message to Brett)",
    ],
    outcome: "Catch cron issues early before they cause missed automations or data gaps.",
    status: "active",
    schedule: "Mondays at 8:00 AM PT",
    livePreview: [
      { label: "Next run", value: "Next Monday 8:00 AM" },
      { label: "Status", value: "All cron jobs healthy" },
    ],
    icon: "🔧",
    tags: ["Monitoring", "Cron", "Health"],
  },
  {
    id: "architecture-review",
    title: "Architecture Review",
    category: "Infrastructure",
    description: "Monthly on the 1st at 9:00 AM, reviews the entire Henry/OpenClaw system: cost efficiency, reliability, data freshness, token usage, missing capabilities, security, updates, performance, memory consolidation, pattern review, and skill audit.",
    howItWorks: [
      "Read AGENTS.md, knowledge-graph.json, ucsd-data-sources.json, MEMORY.md, PATTERNS.md",
      "Run `openclaw status` and `openclaw cron list` to get system state",
      "Analyze and report on 11 areas: cost efficiency, reliability, data freshness, token usage patterns, missing capabilities, security posture, OpenClaw updates, performance, memory consolidation, pattern review, skill audit",
      "For each area, rate: 🟢 Healthy / 🟡 Needs Attention / 🔴 Action Required",
      "End with a prioritized list of 3-5 concrete recommendations",
      "Save to /Users/brettpollak/.openclaw/workspace/docs/architecture-review-$(date +%Y-%m-%d).md",
    ],
    outcome: "Keep the Henry/OpenClaw system healthy, efficient, and aligned with Brett's evolving needs.",
    status: "active",
    schedule: "Monthly on the 1st at 9:00 AM PT",
    livePreview: [
      { label: "Next run", value: "May 1, 9:00 AM" },
      { label: "Last review", value: "April 1" },
    ],
    icon: "🏗️",
    tags: ["Architecture", "Review", "Planning"],
  },
  {
    id: "harness-review",
    title: "Harness Review",
    category: "Infrastructure",
    description: "Quarterly on the 1st of Jan, Apr, Jul, Oct at 10:00 AM, evaluates the Orchestration Assessment pipeline stages: Office Hours, Architect, Builder, Security Review, Evaluator, Deploy, Retro.",
    howItWorks: [
      "Read AGENTS.md to find the Orchestration Assessment and pipeline stages",
      "For each stage, assess: (1) Is this stage still catching real issues? (2) Has a model upgrade made this stage redundant? (3) Can it be simplified or merged? (4) What's the token/cost overhead?",
      "Also check: Are context resets still needed? Is the Evaluator actually rejecting bad work? Are Office Hours adding value?",
      "Produce a brief report with recommendations: KEEP / SIMPLIFY / REMOVE for each stage",
      "Save to /Users/brettpollak/.openclaw/workspace/docs/harness-review-$(date +%Y-%m-%d).md",
    ],
    outcome: "Ensure Brett's Agent pipeline remains effective, efficient, and worth the token investment.",
    status: "active",
    schedule: "Quarterly on the 1st at 10:00 AM PT",
    livePreview: [
      { label: "Next run", value: "July 1, 10:00 AM" },
      { label: "Last review", value: "April 1" },
    ],
    icon: "⚖️",
    tags: ["Review", "Pipeline", "Quality"],
  },
];
